# Generated by Django 5.1.6 on 2025-02-21 12:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstName', models.CharField(help_text="Enter the user's first name.", max_length=255, verbose_name='First Name')),
                ('lastName', models.CharField(help_text="Enter the user's last name.", max_length=255, verbose_name='Last Name')),
                ('phoneNumber', models.CharField(help_text="Enter the user's phone number.", max_length=11, unique=True, verbose_name='Phone Number')),
                ('walletBalance', models.DecimalField(decimal_places=2, help_text="The current balance in the user's wallet.", max_digits=11, verbose_name='Wallet Balance')),
                ('job', models.CharField(choices=[('HC', 'Health Care'), ('TD', 'Taxi Driver'), ('CU', 'Common User')], default='CU', help_text="Select the user's job type.", max_length=2, verbose_name='Job')),
            ],
            options={
                'verbose_name_plural': 'Users',
                'ordering': ['lastName', 'firstName'],
            },
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(auto_now_add=True, help_text='The date of the transaction.', verbose_name='Transaction Date')),
                ('amount', models.DecimalField(decimal_places=2, help_text='The amount of the transaction.', max_digits=9, verbose_name='Amount')),
                ('transactionType', models.CharField(choices=[('W', 'Withdrawal'), ('D', 'Deposit')], default='W', help_text='Select the type of transaction.', max_length=1, verbose_name='Transaction Type')),
                ('receiver', models.ForeignKey(help_text='The user who received the transaction.', on_delete=django.db.models.deletion.PROTECT, related_name='received_transactions', to='daric.user', verbose_name='Receiver')),
                ('sender', models.ForeignKey(help_text='The user who sent the transaction.', on_delete=django.db.models.deletion.PROTECT, related_name='sent_transactions', to='daric.user', verbose_name='Sender')),
            ],
            options={
                'verbose_name_plural': 'Transactions',
                'ordering': ['-date'],
            },
        ),
    ]
