# Generated by Django 5.2b1 on 2025-02-24 20:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('daric', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={},
        ),
    ]
