# Generated by Django 5.2b1 on 2025-02-24 20:33

import uuid
from django.db import migrations, models

def populate_qr_code_id(apps, schema_editor):
    User = apps.get_model('daric', 'User')
    for user in User.objects.all():
        user.qr_code_id = uuid.uuid4()
        user.save()


class Migration(migrations.Migration):

    dependencies = [
        ('daric', '0002_alter_user_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={'ordering': ['lastName', 'firstName'], 'verbose_name_plural': 'Users'},
        ),
        migrations.AddField(
            model_name='user',
            name='qr_code_id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, help_text='Unique ID for generating QR codes.', unique=True, verbose_name='QR Code ID'),
        ),
        migrations.RunPython(populate_qr_code_id),
    ]
