# Generated by Django 5.1.5 on 2025-02-24 20:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('daric', '0003_alter_user_options_user_qr_code_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transaction',
            name='transactionType',
        ),
    ]
