# Generated by Django 5.1.6 on 2025-02-28 08:06

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('daric', '0005_user_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='socialSecureNumber',
            field=models.CharField(default=0, help_text="Enter the user's social security number.", max_length=20, unique=True, verbose_name='Social Secure Number'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='transaction',
            name='amount',
            field=models.DecimalField(decimal_places=2, help_text='The amount of the transaction.', max_digits=9, validators=[django.core.validators.MinValueValidator(0.01)], verbose_name='Amount'),
        ),
        migrations.AlterField(
            model_name='user',
            name='walletBalance',
            field=models.DecimalField(decimal_places=2, default=0, help_text="The current balance in the user's wallet.", max_digits=11, verbose_name='Wallet Balance'),
        ),
    ]
