# Generated by Django 5.1.6 on 2025-02-28 11:56

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('daric', '0007_alter_transaction_options_alter_transaction_amount_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='transaction',
            options={'ordering': ['-date'], 'verbose_name_plural': 'Transactions'},
        ),
        migrations.AlterField(
            model_name='transaction',
            name='amount',
            field=models.DecimalField(decimal_places=2, help_text='The amount of the transaction.', max_digits=9, validators=[django.core.validators.MinValueValidator(0.01)], verbose_name='Amount'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='date',
            field=models.DateField(auto_now_add=True, help_text='The date of the transaction.', verbose_name='Transaction Date'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='receiver',
            field=models.ForeignKey(help_text='The user who received the transaction.', on_delete=django.db.models.deletion.PROTECT, related_name='received_transactions', to='daric.user', verbose_name='Receiver'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='sender',
            field=models.ForeignKey(help_text='The user who sent the transaction.', on_delete=django.db.models.deletion.PROTECT, related_name='sent_transactions', to='daric.user', verbose_name='Sender'),
        ),
    ]
