# Generated by Django 5.1.6 on 2025-03-04 20:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('daric', '0008_alter_transaction_options_alter_transaction_amount_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='default_payment_amount',
            field=models.DecimalField(decimal_places=2, default=0, help_text='The default amount to use for payments. If not provided, it will be 0.', max_digits=9, verbose_name='Default Payment Amount'),
        ),
    ]
