# Generated by Django 5.1.6 on 2025-03-06 19:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('daric', '0009_user_default_payment_amount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='job',
            field=models.CharField(blank=True, choices=[('HC', 'Health Care'), ('TD', 'Taxi Driver'), ('CU', 'Common User')], default='CU', help_text="Select the user's job type.", max_length=2, null=True, verbose_name='Job'),
        ),
    ]
